"""
CleanFlow Example 01: Basic Cleaning
------------------------------------
This script demonstrates the "magic" one-button solution provided by AutomatedCleaner.

It shows:
1. Loading a messy dataset
2. Running the automated cleaning pipeline
3. Comparing data quality before and after
4. Reviewing the cleaning report

Target Audience: Beginners
"""

import pandas as pd
from cleanflow import AutomatedCleaner

def main():
    # 1. Load the sample "messy" data
    # (Generated by scripts/generate_tutorial_data.py)
    input_file = "data/tutorials/tutorial_basic.csv"
    try:
        df = pd.read_csv(input_file)
    except FileNotFoundError:
        print(f"Error: {input_file} not found. Please run 'python scripts/generate_tutorial_data.py' first.")
        return

    print(f"Original DataFrame Shape: {df.shape}")
    print("\n--- Sample Before Cleaning ---")
    print(df.head())

    # 2. Initialize the AutomatedCleaner
    # By default, this enables all cleaning steps:
    # - Type standardization (strings -> numbers/dates/booleans)
    # - Duplicate removal (exact and fuzzy)
    # - Outlier handling (IQR method)
    # - Missing value imputation (median/mode)
    cleaner = AutomatedCleaner()

    # 3. Clean the data
    # The clean() method returns a tuple: (cleaned_dataframe, cleaning_report)
    print("\nRunning automated cleaning pipeline...")
    cleaned_df, report = cleaner.clean(df)

    print(f"\nCleaned DataFrame Shape: {cleaned_df.shape}")
    print("\n--- Sample After Cleaning ---")
    print(cleaned_df.head())

    # 4. Analyze the results
    # The report dictionary contains detailed info about what changed.
    validation = report["validation"]
    initial_q = report["initial_quality"]
    final_q = report["final_quality"]

    print("\n--- Quality Improvements ---")
    print(f"Completeness: {initial_q['completeness_percentage']}% -> {final_q['completeness_percentage']}%")
    print(f"Missing Values: {initial_q['total_missing_values']} -> {final_q['total_missing_values']}")
    print(f"Duplicate Rows: {initial_q['duplicate_rows']} -> {final_q['duplicate_rows']}")
    print(f"Data Loss: {validation['data_loss_pct']}%")
    
    # 5. Review transformations
    # We can inspect specific changes made by transformers
    if "type_conversions" in report:
        print("\n--- Type Conversions Applied ---")
        for conv in report["type_conversions"]:
            print(f"- {conv['column']}: {conv['original_dtype']} -> {conv['new_dtype']}")

if __name__ == "__main__":
    main()
